language: node_js
node_js:
 - "node"
 - "6"

before_script:
 - npm install
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
 - sleep 3 # give xvfb some time to start
script:
 - npm test
