language: node_js
sudo: required
dist: trusty
node_js:
 - "node"
 - "6"

before_script:
 - sudo apt-get install libcurl3-dev
 - npm install
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
 - sleep 3 # give xvfb some time to start
script:
 - npm test
